### ISSUE TITLE
是这样使用么?

### ISSUE THREAD

**Issue by Ansion** [mountainguan/QueryList-DisguisePlugin#1]
$ql = QueryList::getInstance();
$ql->use(DisguisePlugin::class);
$data = $ql->disguiseIp()->disguiseUa()->get($url)->rules($rules)->query()->getData()->all();

**Comment by mountainguan** [comment]
你要使用我fork的QL才能这样操作，基于作者原版的QL缺少钩子入口，我后来修改了，然是pull request过去他不肯接纳...所以，

**方法一，原版的QL配合我这个插件：**
```
$ql = QueryList::getInstance();
$ql->use(DisguisePlugin::class);
$ql->disguiseIp()->disguiseUa()->disguise_headers;//这样生成请求头部的数组，再手动把数据放进去ql对象里
```

**方法二，使用[我fork的QL](https://github.com/mountainguan/QueryList)(添加了头部钩子)：**
```
$ql = QueryList::getInstance();
$ql->use(DisguisePlugin::class);
$ql->disguiseIp()->disguiseUa()->get('http://httpbin.org/get',[
		'param1' => 'testvalue',
		'params2' => 'somevalue'
	],[
 	//设置超时时间，单位：秒
		'timeout' => 30,
		'headers' => [
		 'Referer' => 'https://querylist.cc/',
		'Accept'     => 'application/json',
		'X-Foo'      => ['Bar', 'Baz'],
		 'Cookie'    => 'abc=111;xxx=222'
	]
]);
echo $ql->getHtml();die;
```

**Comment by jae-jae** [comment]
@mountainguan 这个插件挺不错的，QueryList之所以没有接纳你的PR，是因为你的做法不对，你应该在你的插件中对`get()`方法再封装一层加上你自己的逻辑，而不是去修改QueryList的源码。

**Comment by mountainguan** [comment]
这样子，我有空改改，谢谢你的反馈@jae-jae

**Comment by Ansion** [comment]
> 这样子，我有空改改，谢谢你的反馈@jae-jae

大佬，有时间记得改改

**Comment by mountainguan** [comment]
这个一年前的坑，应该是埋了
https://github.com/mountainguan/QLPlugin-DisguisePlugin/commit/0afab9c0be50d741696d3c8553dcb8d8dd62844e
