### ISSUE TITLE
有这个是不是就不用代理了

### ISSUE THREAD

**Issue by moyu2008** [mountainguan/QueryList-DisguisePlugin#2]
有了这个是不是就不用开代理了，只要别人不能识别自己的真实
IP和UA，就限制不了采集了

**Comment by mountainguan** [comment]
...这个怎么说呢，只是一些软性的跳过一些基础的检测。具体还要看你需要采集的页面是走什么规则，有些网站是不给你一个账号多个ip和ua的。所以还是看你自己对那个网站的了解程度，选择性地开和使用
